import test from 'node:test';import assert from 'node:assert/strict';import {createCloudHandler} from '../server-cloud.mjs';
const uid='11111111-1111-4111-8111-111111111111';
const user={id:uid,email:'test@example.in',user_metadata:{name:'Test'}};
const profile={id:uid,name:'Test',experience:'Beginner',regions:[]};
async function request(handler,path,body,cookie='',origin){let text='',headers={};const req={url:'/api/'+path,method:body?'POST':'GET',body,headers:{host:'vanora.test',cookie,...(origin?{origin}:{})},async *[Symbol.asyncIterator](){}};const res={statusCode:0,setHeader:(k,v)=>headers[k]=v,end:s=>text=s};await handler(req,res);return {status:res.statusCode,data:JSON.parse(text),headers};}
const response=(data,status=200)=>({ok:status<400,status,json:async()=>data});
test('cloud sign-up confirmation and sign-in use Supabase Auth and secure server cookies',async()=>{
 let confirmed=false;const calls=[];const h=createCloudHandler({env:{SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'publishable-fixture'},fetcher:async(url,opts)=>{calls.push({url,opts});if(url.includes('/auth/v1/signup'))return response(confirmed?{user,access_token:'access-fixture',refresh_token:'refresh-fixture',expires_in:3600}:{user});if(url.endsWith('/auth/v1/user'))return response(user);if(url.includes('/rest/v1/vanora_profiles'))return response([profile]);return response({})}});
 const pending=await request(h,'signup',{name:'Test',email:'test@example.in',password:'testpassword'});assert.equal(pending.data.confirmationRequired,true);assert.equal(pending.data.user,null);assert.ok(!pending.headers['Set-Cookie']);confirmed=true;
 const signed=await request(h,'signup',{name:'Test',email:'test@example.in',password:'testpassword'});assert.equal(signed.data.user.id,uid);assert.ok(signed.headers['Set-Cookie'].every(c=>c.includes('HttpOnly')&&c.includes('Secure')&&c.includes('SameSite=Lax')));assert.ok(!JSON.stringify(signed.data).includes('access-fixture'));
 const me=await request(h,'me',undefined,'vanora_access=access-fixture');assert.equal(me.data.backend,'supabase');assert.equal(me.data.user.email,user.email);assert.ok(calls.filter(c=>c.url.includes('/rest/')).every(c=>c.opts.headers.Authorization==='Bearer access-fixture'));
});
test('cloud APIs reject unauthenticated writes and cross-origin requests; no local fallback',async()=>{
 const h=createCloudHandler({env:{SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'fixture'},fetcher:async()=>response({})});assert.equal((await request(h,'activities',{})).status,401);assert.equal((await request(h,'signup',{email:'a@b.in',password:'password'},'', 'https://attacker.test')).status,403);assert.equal((await request(h,'demo',{})).status,400);const missing=createCloudHandler({env:{}});assert.equal((await request(missing,'me')).status,503);
});
test('expired cloud sessions refresh without exposing tokens',async()=>{const h=createCloudHandler({env:{SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'fixture'},fetcher:async url=>url.includes('refresh_token')?response({user,access_token:'new-token',refresh_token:'new-refresh',expires_in:3600}):url.includes('/profiles')?response([profile]):response([profile])});const r=await request(h,'me',undefined,'vanora_refresh=old-refresh');assert.equal(r.data.user.id,uid);assert.ok(r.headers['Set-Cookie'][0].includes('new-token'));assert.ok(!JSON.stringify(r.data).includes('new-token'))});
test('activity updates cannot reuse another account’s invisible ID',async()=>{const h=createCloudHandler({env:{SUPABASE_URL:'https://test.supabase.co',SUPABASE_PUBLISHABLE_KEY:'fixture'},fetcher:async url=>url.endsWith('/auth/v1/user')?response(user):url.includes('/vanora_profiles')?response([profile]):response([])});const r=await request(h,'activities',{id:'22222222-2222-4222-8222-222222222222',points:[],seconds:0},'vanora_access=fixture');assert.equal(r.status,403)});
