import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const b=await chromium.launch({channel:'msedge',headless:true});try{
 const c=await b.newContext({viewport:{width:1440,height:1050}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:5173');await p.getByRole('button',{name:'Explore Rajmachi Fort'}).click();await p.getByRole('link',{name:'Nearby care & rest',exact:true}).click();assert.equal(await p.locator('.emergency-call').getAttribute('href'),'tel:112');
 await p.locator('#nearby-approx').click();assert.equal(await p.locator('[name=confirm]').isChecked(),false);await p.locator('[name=confirm]').check();
 const fixture={anchor:{lat:18.826,lng:73.396,radius:25},fetchedAt:new Date().toISOString(),care:[{id:'node/123',name:'Test hospital fixture',kind:'hospital',lat:18.83,lng:73.4,distance:.6,phone:'+91 12345 67890',dial:'+911234567890',address:'Fixture address',hours:'',emergency:'Not documented',edited:null,source:'https://www.openstreetmap.org/node/123'}],rest:[{id:'node/124',name:'Test guest house fixture',kind:'guest_house',lat:18.84,lng:73.41,distance:2,phone:'',dial:null,address:'',hours:'',emergency:'Not documented',edited:null,source:'https://www.openstreetmap.org/node/124'}],truncated:false};
 await p.route('**/api/nearby',async r=>{await new Promise(resolve=>setTimeout(resolve,200));await r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(fixture)})});await p.locator('#nearby-submit').click();await p.getByText('Looking up mapped care and rest places…',{exact:true}).waitFor();await p.getByRole('heading',{name:'Test hospital fixture'}).waitFor();assert.equal(await p.locator('.facility-card').count(),2);assert.match(await p.locator('#nearby-status').innerText(),/straight-line/);await p.locator('#nearby-save').click();await p.screenshot({path:'artifacts/care-desktop.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.locator('#nearby-results').scrollIntoViewIfNeeded();await p.screenshot({path:'artifacts/care-mobile.png'});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await p.unroute('**/api/nearby');await p.route('**/api/nearby',r=>r.fulfill({status:502,contentType:'application/json',body:JSON.stringify({error:'Test provider unavailable. Retry later.'})}));await p.locator('#nearby-submit').click();await p.getByText('Test provider unavailable. Retry later.',{exact:true}).waitFor();assert.equal(await p.locator('.facility-card').count(),0);await p.unroute('**/api/nearby');await p.route('**/api/nearby',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...fixture,care:[],rest:[]})}));await p.locator('#nearby-submit').click();await p.getByText('No hospital or clinic returned',{exact:false}).waitFor();
 await p.reload();await p.getByRole('button',{name:'Explore Rajmachi Fort'}).click();await p.locator('#nearby-load').click();await p.getByRole('heading',{name:'Test hospital fixture'}).waitFor();await c.setOffline(true);await p.locator('#nearby-load').click();assert.match(await p.locator('#nearby-status').innerText(),/Saved snapshot · not live/);await p.locator('#nearby-clear').click();await p.locator('#nearby-load').click();await p.getByText('No usable saved snapshot',{exact:false}).waitFor();assert.deepEqual(errors,[]);console.log('PASS care/rest UI, source/availability labels, consent, fixture loading/error/empty states, snapshot persistence/offline/delete and desktop/mobile layout. No live facility availability asserted.');await c.close();
}finally{await b.close()}
