import {trailImages} from './trail-images.js';
import {sourcedTreks} from './catalogue.js';
import {storiesFor} from './stories.js';
const demoTreks=[
{id:'rajmachi',name:'Rajmachi Fort',area:'Lonavala, Maharashtra',region:'Sahyadris',difficulty:'Moderate',distance:14,gain:680,duration:6,lat:18.826,lng:73.396,season:'October – February',tag:'FORTS & FOREST',image:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85',description:'Follow green ridgelines and forest paths toward twin hill forts, with sweeping views of the Sahyadris.',notes:'Carry sun protection and sturdy footwear. Slippery rock and exposed sections need extra care. Confirm the route and local access before departure.'},
{id:'triund',name:'Triund',area:'McLeod Ganj, Himachal Pradesh',region:'Himalayas',difficulty:'Moderate',distance:9,gain:900,duration:5,lat:32.259,lng:76.354,season:'March – June, September – November',tag:'ALPINE VIEWS',image:'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=1000&q=85',description:'An uphill mountain walk with big Dhauladhar views and a rewarding open ridgeline.',notes:'Mountain weather changes quickly. Carry warm layers and check current local restrictions. Acclimatization and a conservative turnaround time matter.'},
{id:'kudremukh',name:'Kudremukh',area:'Chikkamagaluru, Karnataka',region:'Western Ghats',difficulty:'Challenging',distance:18,gain:1050,duration:8,lat:13.126,lng:75.267,season:'October – February',tag:'ROLLING GRASSLANDS',image:'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1000&q=85',description:'Rolling green grasslands and shola forest make this a memorable, demanding day in the Western Ghats.',notes:'Check current forest entry and guide requirements with local authorities. Plan an early start, rain protection, and a steady pace.'},
{id:'kalsubai',name:'Kalsubai Peak',area:'Bari, Maharashtra',region:'Sahyadris',difficulty:'Challenging',distance:6,gain:800,duration:5,lat:19.601,lng:73.709,season:'October – February',tag:'SUMMIT STORY',image:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1000&q=85',description:'A steep climb above the surrounding hills, with ladder sections and wide summit views.',notes:'Ladders can be crowded and slippery. Avoid exposed sections in poor weather. Confirm access and conditions locally.'},
{id:'dayara',name:'Dayara Bugyal',area:'Uttarkashi, Uttarakhand',region:'Himalayas',difficulty:'Moderate',distance:12,gain:850,duration:7,lat:30.83,lng:78.57,season:'April – June, September – October',tag:'MEADOW DAYS',image:'https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&w=1000&q=85',description:'A high meadow experience framed by Himalayan peaks, with a gradual approach through forest.',notes:'This is a sample day-route distance, not a verified itinerary. Check altitude, acclimatization, permits and guide needs locally.'},
{id:'chembra',name:'Chembra Peak',area:'Wayanad, Kerala',region:'Western Ghats',difficulty:'Easy',distance:5,gain:350,duration:3,lat:11.548,lng:76.088,season:'October – February',tag:'A LITTLE WONDER',image:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1000&q=85',description:'A short, scenic introduction to the forested hills and tea country of Wayanad.',notes:'Public access can change. Verify the currently permitted endpoint and entry rules; this sample is not a summit-access claim.'}
];
export const treks=[...demoTreks.map(t=>({...t,state:t.area.split(', ').at(-1),type:t.id==='rajmachi'?'Fort':t.id==='kudremukh'||t.id==='dayara'?'Meadow':'Mountain',kind:'Demo route',provenance:'demo',source:null,sourceLabel:'Original demonstration catalogue',sourceChecked:null,sourceScope:'Unverified sample values',metricsSource:'Unverified demo',routeStatus:'No verified route geometry'})),...sourcedTreks].map(t=>({...t,stories:storiesFor(t),image:trailImages[t.id].image,imageCredit:trailImages[t.id],imageAlt:trailImages[t.id].kind==='photo'?trailImages[t.id].title+' (Commons photograph; see credit)':t.name+' — original landscape illustration, not a photograph'}));
